UE4.22: Fix compile error C2039: 'IncrementFlushOnDraw': is not a member of 'FSceneViewport'
The Flush On Draw function has been removed from viewports and
frame grabber.

Ref:
- https://github.com/Microsoft/AirSim/issues/1657
- https://github.com/EpicGames/UnrealEngine/commit/ca8f2a2c2494e32c80eaf8940e18cf7c86b54bb

Signed-off-by: Elvis Dowson <elvis.dowson@gmail.com>